[project]
name = "dimwit-python-env"
version = "0.1.0"
description = "Python environment accessible through ScalaPy"
readme = "README.md"
requires-python = "==3.13"
dependencies = [
    "einops>=0.8.1",
    "jax[cuda12]>=0.8.2",
]
